<?php

/**
 * Implements hook_library().
 */
function videojs_youtube_library() {
  $libraries['videojs_youtube'] = array(
    'title' => 'VideoJS Youtube',
    'website' => 'https://github.com/eXon/videojs-youtube',
    'version' => '1.0',
    'js' => array(
      libraries_get_path('videojs-youtube') . '/vjs.youtube.js' => array('weight' => 10),
    ),
  );

  return $libraries;
}

/**
 * Implements hook_field_formatter_info().
 */
function videojs_youtube_field_formatter_info() {
  return array(
    'videojs_youtube' => array(
      'label' => 'VideoJS Youtube',
      'field types' => array('link_field'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view(). This code just passes straight
 */
function videojs_youtube_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  if ($display['type'] !== 'videojs_youtube') {
    return array();
  }
  if (empty($items)) {
    return array();
  }

  drupal_add_library('videojs_youtube', 'videojs_youtube');
  module_load_include('inc', 'videojs', 'includes/videojs.utility');
  $options = videojs_utility::getDefaultDisplaySettings();

  list($id, $vid, $bundle) = entity_extract_ids($entity_type, $entity);
  return array(
    array(
      '#theme' => 'videojs_youtube',
      '#items' => $items,
      '#player_id' => 'videojs-' . $id . '-' . str_replace('_', '-', $instance['field_name']),
      '#options' => $options,
      '#ytcontrols' => 'true',
      '#attached' => videojs_add(FALSE),
    ),
  );
}

/**
 * Implements hook_theme().
 */
function videojs_youtube_theme() {
  return array(
    'videojs_youtube' => array(
      'variables' => array(
        'items' => NULL,
        'player_id' => NULL,
        'options' => array(),
        'ytcontrols' => NULL,
      ),
    ),
  );
}

/*
 * Theme function for age field
 */
function theme_videojs_youtube($vars) {
  $options = $vars['options'];
  /* Unset unnecessary options */
  unset($options['loop'], $options['hidecontrols'], $options['autoplay'], $options['defaulttrack']);
  $options += array(
    'id' => $vars['player_id'],
    'src' => '',
    'class' => 'video-js vjs-default-skin',
  );

  if(isset($vars['options']['hidecontrols']) && $vars['options']['hidecontrols'] != TRUE) {
    $options += array('controls' => 'true');
  }

  $attributes = drupal_attributes($options);

  $data_setup = array('techOrder' => array('youtube'));
  if(isset($options['controls']) && isset($vars['ytcontrols'])) {
    $data_setup += array('ytcontrols' => 'true');
  }

  $output = '';
  foreach($vars['items'] as $item) {
    $data_setup['src'] = $item['url'];
    $encoded_setup = drupal_json_encode($data_setup);
    $encoded_setup = str_replace('\\/', '/', $encoded_setup);
    $output .= "<video {$attributes} data-setup={$encoded_setup}></video>";
  }

  return $output;
}
